### PR TITLE
Make this work with Omnipay 3 and Symfony 3.4.

### PR DESCRIPTION
**Pull request by noud**
hi Colin,

i did some small patches to get this bundle working with
Omnipay 3 and Symfony 3.4.

I did test and everything still works.

Would you please be so kind to accept this pull request?

thanks,
Noud

### CODE REVIEW

**Comment by colinodell** [comment]
Thanks for the contribution!  I'd like to get this merged in, probably sometime later this week.  If I forget then please feel free to remind me next week :upside_down_face:

**Comment by noud** [comment]
Colin,
thanks already for merging later this week!

i see Scrutinizer erroring about:
omnipay/common v3.0.2 requires php-http/client-implementation ^1 -> no matching package found.

i got this also fixed, see:
https://github.com/noud/omnipay-common/commit/3384cf442accb871d75a7d3390e2f20986ab0095

and i filed a pull request for it:
https://github.com/thephpleague/omnipay-common/pull/200

greetings,
Noud

**Comment by noud** [comment]
hi Colin,
you told me i may remind you this week for the merge ;)

(O and the client-implementation, to my understanding now,
this is a virtual package that does come with other client implementations.)

greetings and a nice week,
Noud

**Comment by noud** [comment]
thank you.

**Pull request merged**
