### PR TITLE
Extend configuration and make customization easier

### PR DESCRIPTION
**Pull request by torchello**
This PR aims to make the bundle more flexible and easier to customize. Please see updated `README.md` for details. I would also propose to create new `0.3.0` tag.

PS. All changes are based on a real project needs.

### CODE REVIEW

**Comment by colinodell** [comment]
I really like the proposed improvements!  I'll take a closer look at this today or tomorrow and let you know if I have any feedback.

**Comment by torchello** [comment]
@colinodell Any feedback?

**Comment by colinodell** [comment]
Sorry for the delay, everything looks great!  I've merged in your changes and will release `0.3.0` momentarily.

Thanks so much for the contribution!

**Comment by colinodell** [comment]
Released: https://github.com/colinodell/omnipay-bundle/releases/tag/0.3.0

**Pull request merged**
